#!/bin/bash

<<comment
Trying Error handeling in script, here error hendaling means , if user input a file name which is not present the script will not run further, it will exit with code 1.
comment

file=$1

if [ -e "$file" ];  then 
echo "file is  present"
else
	echo "file $file not present"
	exit 1
fi

echo "--------------------We Answer your querry------------------------"
